trigger:
  branches:
    include:
      - '*'
  tags:
    include:
      - '*'

stages:
- stage: Build
  jobs:
    - job: Linux

      pool:
        vmImage: ubuntu-16.04

      steps:
        - task: Gradle@2
          displayName: 'Check'
          inputs:
            workingDirectory: ''
            gradleWrapperFile: 'gradlew'
            gradleOptions: '-Xmx3072m'
            options: '--stacktrace -PlogTests -Pheadless'
            javaHomeOption: 'JDKVersion'
            jdkVersionOption: '1.11'
            jdkArchitectureOption: 'x64'
            publishJUnitResults: true
            testResultsFiles: '**/TEST-*.xml'
            tasks: 'check'

        - task: Gradle@2
          displayName: 'JacocoRootReport'
          inputs:
            workingDirectory: ''
            gradleWrapperFile: 'gradlew'
            gradleOptions: '-Xmx3072m'
            options: '--stacktrace -PlogTests -Pheadless'
            javaHomeOption: 'JDKVersion'
            jdkVersionOption: '1.11'
            jdkArchitectureOption: 'x64'
            publishJUnitResults: true
            testResultsFiles: '**/TEST-*.xml'
            tasks: 'jacocoRootReport'

        - bash: bash <(curl -s https://codecov.io/bash) || echo 'Codecov failed to upload'
          displayName: 'CodeCov'
          workingDirectory: ''
          env:
            CODECOV_TOKEN: $(CODECOV_TOKEN)

    - job: MacOS

      pool:
        vmImage: macOS-10.14

      steps:
        # The latest version of docker is broken so we need to install an older one
        # https://github.com/docker/for-mac/issues/2359
        - script: |
            DOCKER_URL=https://download.docker.com/mac/stable/31259/Docker.dmg
            curl -O -sSL $DOCKER_URL
            open -W Docker.dmg && cp -r /Volumes/Docker/Docker.app /Applications

            sudo /Applications/Docker.app/Contents/MacOS/Docker --quit-after-install --unattended
            nohup /Applications/Docker.app/Contents/MacOS/Docker --unattended &

            while ! docker ps 2>/dev/null ; do
            sleep 5
            echo "Waiting for docker to come up: $(date)"
            done
          displayName: 'Install Docker'

        - task: Gradle@2
          displayName: 'Check'
          inputs:
            workingDirectory: ''
            gradleWrapperFile: 'gradlew'
            gradleOptions: '-Xmx3072m'
            options: '--stacktrace -PlogTests -Pheadless'
            javaHomeOption: 'JDKVersion'
            jdkVersionOption: '1.11'
            jdkArchitectureOption: 'x64'
            publishJUnitResults: false
            tasks: 'check'

        - task: Gradle@2
          displayName: 'JacocoRootReport'
          inputs:
            workingDirectory: ''
            gradleWrapperFile: 'gradlew'
            gradleOptions: '-Xmx3072m'
            options: '--stacktrace -PlogTests -Pheadless'
            javaHomeOption: 'JDKVersion'
            jdkVersionOption: '1.11'
            jdkArchitectureOption: 'x64'
            publishJUnitResults: true
            testResultsFiles: '**/TEST-*.xml'
            tasks: 'jacocoRootReport'

    - job: Windows

      pool:
        vmImage: windows-2019

      steps:
#        - powershell: "Install-Module -Name DockerMsftProvider -Repository PSGallery -Force"
#          displayName: 'InstallDockerProvider'
#
#        - powershell: "Install-Package -Name docker -ProviderName DockerMsftProvider -Force -RequiredVersion 19.03"
#          displayName: 'InstallDocker'
#
#        - powershell: "Start-Service docker"
#          displayName: 'StartDocker'

        - powershell: "choco install docker-desktop -y --version=2.1.0.3"

        - powershell: "& (Join-Path -Path (Get-Item ((Get-Command docker.exe).Source)).Directory.Parent.Parent.FullName -ChildPath \"DockerCli.exe\") -SwitchLinuxEngine"
          displayName: 'SwitchLinux'

        - task: Gradle@2
          displayName: 'Check'
          inputs:
            workingDirectory: ''
            gradleWrapperFile: 'gradlew'
            gradleOptions: '-Xmx3072m'
            options: '--stacktrace -PlogTests -Pheadless'
            javaHomeOption: 'JDKVersion'
            jdkVersionOption: '1.11'
            jdkArchitectureOption: 'x64'
            publishJUnitResults: false
            tasks: 'check'

        - task: Gradle@2
          displayName: 'JacocoRootReport'
          inputs:
            workingDirectory: ''
            gradleWrapperFile: 'gradlew'
            gradleOptions: '-Xmx3072m'
            options: '--stacktrace -PlogTests -Pheadless'
            javaHomeOption: 'JDKVersion'
            jdkVersionOption: '1.11'
            jdkArchitectureOption: 'x64'
            publishJUnitResults: true
            testResultsFiles: '**/TEST-*.xml'
            tasks: 'jacocoRootReport'
